- name: Create EC2 and Route 53 records
  hosts: localhost
  vars:
    zone: dharla.online
    instances:
      - db
      - backend
      - frontend
  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        instance_type: t2.micro
        name: "{{ item }}"
        security_groups:
          - sg-042ad1e82e90ec91b
        image_id: ami-041e2ea9402c46c32
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_instances_info

    - name: Print EC2 instance information
      ansible.builtin.debug:
        msg: "{{ ec2_instances_info }}"

    - name: Create Route 53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.tags.Name }}.{{ zone }}"
        type: A
        value: "{{ item.private_ip }}"
        overwrite: true
        ttl: 1
      loop: "{{ ec2_instances_info.instances }}"
      loop_control:
        loop_var: item

    - name: Debug EC2 Instances Info
      ansible.builtin.debug:
        var: ec2_instances_info

